Spring:
  application:
    name: zuul-server
server:
  port: 8080

spring:
  boot:
    admin:
      url: http://localhost:9002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9991/eureka/

zuul:
  routes:
    user:
      path: /user/**
      service-id: user-service
    auth:
      path: /auth/**
      service-id: auth-service