Spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888/
      profile: dev
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9991/eureka/
